# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: opus667/pepaDEVbr

media_folder: /src/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: /src/content/blog
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
