# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: opus667/pepaDEVbr

media_folder: /src/assets/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    folder: /src/content/blog
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: "Criado em", name: "pubDate", widget: "datetime" }
      - { label: "Destaque", name: "heroImage", widget: "image" }
      - { label: Content, name: body, widget: markdown }
